---
title: "make order abundance label over KO level3 and time"
author: "xyz"
date: "2021/8/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The function components of most Orders keep stable over eight time points. But the Oder components of most function change a lot over eight time points. The abundance change of different taxonomies may reason the functional change of gut microbiota.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(stringr)
library(tidyr)
library(xlsx)
library(vegan)
```

```{r}
eset.f <-
  as.data.frame(readRDS("../only protein with KEGG/eset.f.rds"))
abundance <- cbind.data.frame(Protein = rownames(eset.f), eset.f)
speciesDf <-
  read_xlsx("../SuppTable 5 Protein Family Annotation(1).xlsx")
speciesDf <-
  data.frame(Protein = speciesDf[-1:-2, 1, drop = TRUE],
             KO = speciesDf[-1:-2, 4, drop = TRUE],
             Tax = speciesDf[-1:-2, 6, drop = TRUE])
speciesDf$Tax <- str_split(speciesDf$Tax, ";", simplify = T)[, 4]

keggLevel <- readRDS("KEGG 4 level results.rds")
keggLevel <- keggLevel[, c(3, 5)]
keggLevel$level4 <- str_sub(keggLevel$level4, end = 6)
keggLevel$level2 <- str_sub(keggLevel$level2, start = 7)
keggLevel <- unique(keggLevel)

abundanceDf <-
  right_join(speciesDf, abundance, by = c("Protein" = "Protein"))
abundanceDf <-
  right_join(keggLevel, abundanceDf[, -1], by = c("level4" = "KO"))
abundanceDf <- abundanceDf[, -2]
abundanceDf <- abundanceDf[abundanceDf$Tax!="" & abundanceDf$Tax!="unknown", ]
abundanceDf <- group_by(abundanceDf,level2,Tax)
abundanceDf <- summarise(abundanceDf,across(everything(),sum))
top10<-as.data.frame(sort(table(abundanceDf$level2),decreasing = T))
top10<-as.character(top10[c(1:6,8:11),1])
abundanceDf<- abundanceDf[abundanceDf$level2 %in% top10,]

abundanceDf <- pivot_wider(abundanceDf,Tax,names_from = level2, 
                           values_from = T3_5:T30_35, names_sep = ";")
abundanceDf[is.na(abundanceDf)]<-0
abundanceDf <- as.data.frame(abundanceDf)
rownames(abundanceDf)<- abundanceDf$Tax
abundanceDf <- prop.table(as.matrix(abundanceDf[,-1]),2)

meta <- as.data.frame(str_split(colnames(abundanceDf),";",simplify = T))
colnames(meta)<-c("Time","KEGG")
meta$Time<-factor(meta$Time,levels = colnames(eset.f))
pca<-rda(t(abundanceDf),scale=T)
importance <- summary(pca)[["cont"]][["importance"]]
siteScore <- summary(pca)[["sites"]]
tempDf <- cbind(x = siteScore[, 1],
                y = siteScore[, 2],
                meta)

p <- ggplot(tempDf,
            aes(
              x = x,
              y = y,
              color = Time,
              shape = KEGG
            )) +
  scale_shape_manual(values = 1:10, name = "KEGG level 3") +
  geom_point(size = 3) +
  xlab(paste0("Taxonomic Profile PC1(", round(importance[2, 1] * 100, 2), "%)")) +
  ylab(paste0("Taxonomic Profile PC2(", round(importance[2, 2] * 100, 2), "%)")) +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 0.7
    )
  )
p + ggsave("Order over time and KEGG PCA.pdf",width = 10, height = 6)
```

# chisqure test

all p is 1

```{r}
KEGG<-unique(meta$KEGG)
chiResult<-data.frame()
for (i in KEGG){
  testTable<-abundanceDf[,meta$KEGG==i]
  testTable<-testTable[rowSums(testTable)>0,]
  chi<-chisq.test(testTable)
  chiResult<-rbind(chiResult,c("KEGG"=i,"p"=chi$p.value))
}
colnames(chiResult)<-c("KEGG","p")

Time<-unique(meta$Time)
chiResultTime<-data.frame()
for (i in Time){
  testTable<-abundanceDf[,meta$Time==i]
  testTable<-testTable[rowSums(testTable)>0,]
  chi<-chisq.test(testTable)
  chiResultTime<-rbind(chiResultTime,c("Time"=i,"p"=chi$p.value))
}
colnames(chiResultTime)<-c("Time","p")
```

# MRPP

KEGG's difference is not
Time's difference is significant

```{r}
# p=0.134
set.seed(9257)
mrpp(t(abundanceDf), meta$KEGG, distance = 'bray', permutations = 999)
# p=0.001
set.seed(9257)
mrpp(t(abundanceDf), meta$Time, distance = 'bray', permutations = 999)
```